import std/os
import kksg/[gtk, ui, qr, viewer]
let app = adw_application_new("org.kks.DlgTest", 32)
app.on("activate", proc () =
  let w = adw_application_window_new(app)
  gtk_window_set_default_size(w, 1280, 820)
  let to = adw_toast_overlay_new()
  let v = newViewer()
  adw_toast_overlay_set_child(to, v.widget)
  adw_application_window_set_content(w, to)
  gtk_window_present(w)
  timeout(2000, proc (): bool =
   let d = adw_dialog_new()
   adw_dialog_set_title(d, "Nim dialog")
   let body = vbox(10)
   let tex = qrTexture("{\"kks_invite\":2,\"x\":1}")
   let pic = gtk_picture_new_for_paintable(tex)
   gtk_widget_set_size_request(pic, 320, 320)
   setAccessibleLabel(pic, "QR code of the invite")
   body.add pic
   body.add label("hello from nim", "dim-label")
   if paramCount() > 0: body.add label("{\"kks_invite\":2}", "monospace caption", selectable = true)
   body.add button("Copy", "", proc () = discard)
   let sc = scrolled(body)
   gtk_scrolled_window_set_propagate_natural_height(sc, 1)
   adw_dialog_set_content_height(d, 720)
   adw_dialog_set_child(d, toolbarView(headerBar(adw_window_title_new("Add a device", "")), sc))
   adw_dialog_present(d, w)
   false))
discard g_application_run(app, 0, nil)
